title:             A.Onur Demir
author:            A.Onur Demir
description:       
baseurl:           "/"
url:               "http://aonurdemir.github.io"

# Social Profiles
twitter_username:  aonurdemir
github_username:   aonurdemir
facebook_username: aonurdemir

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
